# Generated by Django 5.2.4 on 2025-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
