# Generated by Django 5.2.4 on 2025-07-10 08:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_code_alter_historicalcustomer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(max_length=20, unique=True)),
                ('posting_date', models.DateField()),
                ('document_no', models.CharField(max_length=30)),
                ('document_type', models.CharField(blank=True, max_length=30)),
                ('block_reason', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Ledger Entry',
                'verbose_name_plural': 'Customer Ledger Entries',
                'ordering': ['-entry_no'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomerLedgerEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('entry_no', models.CharField(db_index=True, max_length=20)),
                ('posting_date', models.DateField()),
                ('document_no', models.CharField(max_length=30)),
                ('document_type', models.CharField(blank=True, max_length=30)),
                ('block_reason', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Customer Ledger Entry',
                'verbose_name_plural': 'historical Customer Ledger Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
