# Generated by Django 5.2.4 on 2025-07-17 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerledgerentry_historicalcustomerledgerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer'),
        ),
    ]
